version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17-buster-browsers-legacy
    working_directory: ~/repo
    web:
      environment:
        - NETWORK
        - PROVIDER
        - URL
        - PRIVATE_KEY
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "What are my custom variables?"
          command: echo ${NETWORK} ${PROVIDER}
      - run: yarn test
      - run: yarn chromatic test --app-code=<app-code> --exit-zero-on-changes
